version: '2'
services:
  nginx:
    image: opsway/webserver:nginx
    environment:
    - DOMAIN=${sandbox_key}.boodmo.opsway-dev.com
    - APPLICATION_ENV=dev
    - PROTO=http
    - 'HTTP_AUTH=opsway:$$apr1$$JrTqxzFl$$68H8lccyXDEj9K2BlaCuC1'
    stdin_open: true
    tty: true
    links:
    - phpfpm:phpfpm
    volumes_from:
    - phpfpm
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: phpfpm
      io.rancher.container.hostname_override: container_name

  phpfpm:
    image: opswaycom/boodmo-app
    environment:
      DOMAIN: ${sandbox_key}.boodmo.opsway-dev.com
      DATABASE_PORT_5432_TCP_ADDR: database
      DATABASE_PORT_5432_TCP_PORT: 5432
      DATABASE_NAME: ${database_name}
      DATABASE_USER: ${database_user}
      DATABASE_PASS: ${database_pass}
      CACHE_PORT_6379_TCP_ADDR: cache
      CACHE_PORT_6379_TCP_PORT: 6379
      SESSION_PORT_6379_TCP_ADDR: session
      SESSION_PORT_6379_TCP_PORT: 6379
      ELASTICSEARCH2_PORT_9200_TCP_ADDR: elasticsearch2
      ELASTICSEARCH2_PORT_9200_TCP_PORT: 9200
      CACHE_TYPE: array
      PROTO: http
    working_dir: /app
    links:
    - elasticsearch2:elasticsearch2
    - cache:cache
    - session:session
    - database:database
    stdin_open: true
    command:
    - php-fpm
    volumes:
    - /var/www/srv/${sandbox_key}/app:/app
    - /var/www/frontend/shared/public/media:/app/public/media
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
  database:
    image: opsway/webserver:postgres
    environment:
      POSTGRES_DB: ${database_name}
      POSTGRES_PASSWORD: ${database_user}
      POSTGRES_USER: ${database_pass}
    volumes:
    - /var/www/srv/${sandbox_key}/pgdata:/var/lib/postgresql/data
  cache:
    image: redis:3
  session:
    image: redis:3
  elasticsearch2:
    image: elasticsearch:2
    command:
    - -Des.discovery.zen.ping.multicast.enabled=false
    volumes:
    - /var/www/srv/${sandbox_key}/esdata:/usr/share/elasticsearch/data